Repository joomlatools/joomlatools-pages, pull requests merged in 2019-07, with the labels that each got.

#147 Add snippets support
  code/site/components/com_pages/template/default.php
  code/site/components/com_pages/template/helper/snippet.php
Labels: feature

#151 route() should return a string
  code/site/components/com_pages/view/html.php
  code/site/components/com_pages/view/json.php
  code/site/components/com_pages/view/xml.php
Labels: bug

#155 #154: proposed fix
  code/site/components/com_pages/view/html.php
Labels: bug

#163 Refactor config handling
  code/site/components/com_pages/config.php
  code/site/components/com_pages/data/client.php
  code/site/components/com_pages/data/locator.php
  code/site/components/com_pages/data/registry.php
  code/site/components/com_pages/dispatcher/behavior/cacheable.php
  code/site/components/com_pages/dispatcher/router/resolver/site.php
  code/site/components/com_pages/page/locator.php
  code/site/components/com_pages/page/registry.php
  code/site/components/com_pages/resources/config/bootstrapper.php
  code/site/components/com_pages/resources/config/site.php
Labels: refactor

#161 Form support
  code/site/components/com_pages/controller/behavior/processable.php
  code/site/components/com_pages/controller/behavior/validatable.php
  code/site/components/com_pages/controller/collection.php
  code/site/components/com_pages/controller/exception/requestblocked.php
  code/site/components/com_pages/controller/exception/requestinvalid.php
  code/site/components/com_pages/controller/exception/spam.php
  code/site/components/com_pages/controller/form.php
  code/site/components/com_pages/controller/permission/collection.php
  code/site/components/com_pages/controller/permission/form.php
  code/site/components/com_pages/controller/processor/abstract.php
  code/site/components/com_pages/controller/processor/csv.php
  code/site/components/com_pages/controller/processor/database.php
  code/site/components/com_pages/controller/processor/email.php
  code/site/components/com_pages/controller/processor/interface.php
  code/site/components/com_pages/database/table/abstract.php
  code/site/components/com_pages/database/table/default.php
  code/site/components/com_pages/dispatcher/behavior/decoratable.php
  code/site/components/com_pages/dispatcher/http.php
  code/site/components/com_pages/dispatcher/router/router.php
  code/site/components/com_pages/event/subscriber/errorhandler.php
  code/site/components/com_pages/model/database.php
  code/site/components/com_pages/model/entity/page.php
  code/site/components/com_pages/page/object.php
  code/site/components/com_pages/page/registry.php
  code/site/components/com_pages/template/filter/form.php
  code/site/components/com_pages/template/filter/meta.php
  code/site/components/com_pages/template/helper/form.php
  code/site/components/com_pages/template/helper/snippet.php
Labels: refactor

#160 CSV support
  code/site/components/com_pages/model/factory.php
  code/site/components/com_pages/model/filesystem.php
  code/site/components/com_pages/object/config/csv.php
  code/site/components/com_pages/resources/config/bootstrapper.php
  code/site/components/com_pages/view/collection/csv.php
  code/site/components/com_pages/view/csv.php
Labels: feature
