Repository joomlatools/joomlatools-pages, pull requests merged in 2019-03, with the labels that each got.

#59 #58: Require an ID for header elements
  code/site/components/com_pages/template/filter/toc.php
  code/site/components/com_pages/template/helper/behavior.php
Labels: bug

#61 Content plugins page filter
  code/site/components/com_pages/model/entity/page.php
  code/site/components/com_pages/template/filter/plugins.php
  code/site/components/com_pages/view/page/html.php
Labels: refactor

#64 Remote collections
  code/site/components/com_pages/controller/abstract.php
  code/site/components/com_pages/data/client.php
  code/site/components/com_pages/data/registry.php
  code/site/components/com_pages/model/collection.php
  code/site/components/com_pages/model/factory.php
  code/site/components/com_pages/model/page.php
  code/site/components/com_pages/model/pages.php
  code/site/components/com_pages/model/remote.php
  code/site/components/com_pages/resources/config/bootstrapper.php
  code/site/components/com_pages/view/html.php
  code/site/components/com_pages/view/json.php
  code/site/components/com_pages/view/xml.php
Labels: feature

#66 Fix limit issue
  code/site/components/com_pages/dispatcher/http.php
Labels: bug

#70 Add http_cache_time_proxy setting
  code/site/components/com_pages/dispatcher/behavior/cacheable.php
  code/site/components/com_pages/resources/config/bootstrapper.php
Labels: feature

#68 Fix route('index')
  code/site/components/com_pages/dispatcher/router/resolver/abstract.php
  code/site/components/com_pages/dispatcher/router/resolver/page.php
  code/site/components/com_pages/page/registry.php
  code/site/components/com_pages/view/html.php
  code/site/components/com_pages/view/json.php
  code/site/components/com_pages/view/xml.php
Labels: bug

#72 Database collections
  code/site/components/com_pages/model/behavior/accessible.php
  code/site/components/com_pages/model/behavior/categorizable.php
  code/site/components/com_pages/model/behavior/collectable.php
  code/site/components/com_pages/model/behavior/crawlable.php
  code/site/components/com_pages/model/behavior/dateable.php
  code/site/components/com_pages/model/behavior/filterable.php
  code/site/components/com_pages/model/behavior/paginatable.php
  code/site/components/com_pages/model/behavior/queryable.php
  code/site/components/com_pages/model/behavior/searchable.php
  code/site/components/com_pages/model/behavior/sortable.php
  code/site/components/com_pages/model/behavior/visible.php
  code/site/components/com_pages/model/collection.php
  code/site/components/com_pages/model/context/collection.php
  code/site/components/com_pages/model/database.php
  code/site/components/com_pages/model/interface.php
  code/site/components/com_pages/model/pages.php
  code/site/components/com_pages/model/webservice.php
Labels: feature

#76 Controller collections
  code/site/components/com_pages/model/controller.php
  code/site/components/com_pages/model/factory.php
Labels: feature

#74 Filesystem collections
  code/site/components/com_pages/data/registry.php
  code/site/components/com_pages/model/filesystem.php
  code/site/components/com_pages/template/default.php
Labels: feature
