Repository joomlatools/joomlatools-pages, pull requests merged in 2020-05, with the labels that each got.

#327 Add a default pages collection
  code/site/components/com_pages/page/registry.php
Labels: feature, refactor

#329 Add support for multi-dimensional data to CSV form processor
  code/site/components/com_pages/controller/processor/csv.php
Labels: feature, refactor

#331 Add ComPagesCollection::getName() method
  code/site/components/com_pages/model/collection.php
  code/site/components/com_pages/model/factory.php
Labels: feature

#333 Allow to configure data root path for a webservice collection
  code/site/components/com_pages/model/webservice.php
Labels: feature

#335 Improve webhook processor
  code/site/components/com_pages/controller/processor/webhook.php
Labels: refactor

#336 Set cache folders to 0777
  code/site/components/com_pages/data/registry.php
  code/site/components/com_pages/dispatcher/behavior/cacheable.php
  code/site/components/com_pages/http/client.php
  code/site/components/com_pages/page/registry.php
Labels: feature

#338 Division by zero error when limit is 0
  code/site/components/com_pages/dispatcher/router/resolver/pagination.php
Labels: bug

#340 Do not filter decorated component content
  code/site/components/com_pages/event/subscriber/pagedecorator.php
Labels: bug, refactor

#342 Joomla login no longer working
  code/site/components/com_pages/event/subscriber/dispatcher.php
Labels: bug

#350 Fix Travis script
  .travis.yml
  scripts/build/pack.sh
Labels: refactor

#352 Use identifiers when registering config formats
  code/site/components/com_pages/resources/config/bootstrapper.php
Labels: refactor
